DROP DATABASE IF EXISTS JARDINS_PUBLICS;
CREATE DATABASE JARDINS_PUBLICS;
SHOW DATABASES;
USE JARDINS_PUBLICS;

CREATE TABLE DISTRICTE (
	Codi INT NOT NULL,
    Denominació VARCHAR(100) NOT NULL UNIQUE
);
CREATE TABLE BARRI (
	Codi INT NOT NULL,
    Denominació VARCHAR(100) NOT NULL UNIQUE,
	Habitants INT,
    Superfície DECIMAL(10,2),
    CodiDistricte INT
);
CREATE TABLE SECTOR (
	Codi INT NOT NULL,
    Superfície DECIMAL(10,2),
    Superfície_zona_verda DECIMAL(10,2),
    CodiBarri INT
);

CREATE TABLE PLANTA (
	Codi INT NOT NULL,
    NomComú VARCHAR(100),
    NomCientífic VARCHAR(100),
    condicionsCreixement VARCHAR(255)
);

CREATE TABLE COMPATIBLE (
	CodiPlanta1 INT,
    CodiPlanta2 INT
);
CREATE TABLE TROBEM (
	CodiSector INT NOT NULL,
    CodiPlanta INT NOT NULL
);
CREATE TABLE EMPRESA (
	CIF CHAR(9) NOT NULL,
    Denominació VARCHAR(100),
	Telefon CHAR(10)
);
CREATE TABLE CONCESSIÓ (
	CIF CHAR(9) NOT NULL,
    CodiSector INT NOT NULL,
    Data_inici DATE,
    Data_fi DATE
);
CREATE TABLE DATA (
	Data DATE
);

CREATE TABLE TREBALLADOR (
	DNI CHAR(9) NOT NULL, 
    Nom VARCHAR(50), 
    Cognoms VARCHAR(100), 
    NSS INT, 
    Telefon CHAR(10)
);
CREATE TABLE TREBALLA (
	DNI CHAR(9) NOT NULL, 
    Data_inici DATE,
    Data_fi DATE
);
CREATE TABLE ADMINISTRACIÓ (
	DNI CHAR(9) NOT NULL, 
    areaResponsabilitat VARCHAR(100), 
    CompetènciesTècniques VARCHAR(255)
);
CREATE TABLE TÈCNICS (
	DNI CHAR(9) NOT NULL, 
    Especialització VARCHAR(100)
);
CREATE TABLE JARDINERS (
	DNI CHAR(9) NOT NULL
);
CREATE TABLE dissenyJardins (
	Codi INT NOT NULL,
    Denominació VARCHAR(100),
    pressupost DECIMAL(10,2),
    Ubicació VARCHAR(255)
);
CREATE TABLE TREBALLEN (
	DNI CHAR(9) NOT NULL,
    Codi_dissenyJardins INT
);

-- Claves primarias
ALTER TABLE DISTRICTE ADD PRIMARY KEY (Codi);

ALTER TABLE BARRI ADD PRIMARY KEY (Codi);

ALTER TABLE SECTOR ADD PRIMARY KEY (Codi);

ALTER TABLE PLANTA ADD PRIMARY KEY (Codi);

ALTER TABLE COMPATIBLE ADD PRIMARY KEY (CodiPlanta1, CodiPlanta2);

ALTER TABLE TROBEM ADD PRIMARY KEY (CodiSector, CodiPlanta);

ALTER TABLE EMPRESA ADD PRIMARY KEY (CIF);

ALTER TABLE CONCESSIÓ ADD PRIMARY KEY (CIF, CodiSector, Data_inici);

ALTER TABLE DATA ADD PRIMARY KEY (Data);

ALTER TABLE TREBALLADOR ADD PRIMARY KEY (DNI);

ALTER TABLE TREBALLA ADD PRIMARY KEY (DNI, Data_inici);

ALTER TABLE ADMINISTRACIÓ ADD PRIMARY KEY (DNI);

ALTER TABLE TÈCNICS ADD PRIMARY KEY (DNI);

ALTER TABLE JARDINERS ADD PRIMARY KEY (DNI);

ALTER TABLE dissenyJardins ADD PRIMARY KEY (Codi);

ALTER TABLE TREBALLEN ADD PRIMARY KEY (DNI, Codi_dissenyJardins);

-- Claves foráneas

ALTER TABLE BARRI
ADD CONSTRAINT FK_Barri_Districte
FOREIGN KEY (CodiDistricte) REFERENCES DISTRICTE(Codi);

ALTER TABLE SECTOR
ADD CONSTRAINT FK_Sector_Barri
FOREIGN KEY (CodiBarri) REFERENCES BARRI(Codi);

ALTER TABLE TROBEM
ADD CONSTRAINT FK_Trobem_Sector
FOREIGN KEY (CodiSector) REFERENCES SECTOR(Codi),
ADD CONSTRAINT FK_Trobem_Planta
FOREIGN KEY (CodiPlanta) REFERENCES PLANTA(Codi);

ALTER TABLE COMPATIBLE
ADD CONSTRAINT FK_Compatible_Planta1
FOREIGN KEY (CodiPlanta1) REFERENCES PLANTA(Codi),
ADD CONSTRAINT FK_Compatible_Planta2
FOREIGN KEY (CodiPlanta2) REFERENCES PLANTA(Codi);

ALTER TABLE CONCESSIÓ
ADD CONSTRAINT FK_Concessio_Empresa
FOREIGN KEY (CIF) REFERENCES EMPRESA(CIF),
ADD CONSTRAINT FK_Concessio_Sector
FOREIGN KEY (CodiSector) REFERENCES SECTOR(Codi);

ALTER TABLE TREBALLA
ADD CONSTRAINT FK_Treballa_Treballador
FOREIGN KEY (DNI) REFERENCES TREBALLADOR(DNI),
ADD CONSTRAINT FK_Treballa_Data
FOREIGN KEY (administracióData_inici) REFERENCES DATA(Data);

ALTER TABLE ADMINISTRACIÓ
ADD CONSTRAINT FK_Administracio_Treballador
FOREIGN KEY (DNI) REFERENCES TREBALLADOR(DNI);

ALTER TABLE TÈCNICS
ADD CONSTRAINT FK_Tecnics_Treballador
FOREIGN KEY (DNI) REFERENCES TREBALLADOR(DNI);

ALTER TABLE JARDINERS
ADD CONSTRAINT FK_Jardiners_Treballador
FOREIGN KEY (DNI) REFERENCES TREBALLADOR(DNI);

ALTER TABLE TREBALLEN
ADD CONSTRAINT FK_Treballen_Treballador
FOREIGN KEY (DNI) REFERENCES TREBALLADOR(DNI),
ADD CONSTRAINT FK_Treballen_dissenyJardins
FOREIGN KEY (Codi_dissenyJardins) REFERENCES dissenyJardins(Codi);